export class RouterPath {
  static readonly SPLASH = 'features/auth/pages/SplashPage'
  static readonly LOGIN = 'features/auth/pages/LoginPage'
  static readonly STUDENT_HOME = 'features/student/pages/StudentHomePage'
  static readonly BREATHING = 'features/student/pages/BreathingPage'
  static readonly ATTENTION = 'features/student/pages/AttentionPage'
  static readonly RHYTHM = 'features/student/pages/RhythmPage'
  static readonly MOOD_CHECK_IN = 'features/student/pages/MoodCheckInPage'
  static readonly WAVEFORM = 'features/student/pages/WaveformPage'
  static readonly SEMI_MONTHLY = 'features/student/pages/SemiMonthlyPage'
  static readonly APPOINTMENT = 'features/student/pages/AppointmentPage'
  static readonly ACTIVITY = 'features/student/pages/ActivityPage'
  static readonly PROFILE = 'features/student/pages/ProfilePage'
}
